[tool.poetry]
name = "terraform-worker"
version = "0.11.0"
description = "An orchestration tool for Terraform"
authors = ["Richard Maynard <richard.maynard@gmail.com>"]
packages = [
    { include="tfworker", from="." },
]
readme = "README.md"

repository = "https://github.com/ephur/terraform-worker"
homepage = "https://github.com/ephur/terraform-worker"
documentation = "https://github.com/ephur/terraform-worker"

license = "Apache-2.0"

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Topic :: System :: Systems Administration"
]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.26.8"
click = "^8.1.3"
awscli = "^1.27.94"
jinja2 = "^3.1"
tenacity = "^8.2.2"
requests = "^2.28"
google-cloud-storage = "^2.7.0"
python-hcl2 = "^4.3.0"
lark = "^1.1"
pyyaml = "^5.4"
markupsafe = "2.1"
mergedeep = "1.3.4"
setuptools = "67.6.0"

[tool.poetry.dev-dependencies]
ipython = "^8.11.0"
pytest = "^7.2.0"
black = "^23.1"
isort = "^5.12"
seed-isort-config = "^2.2.0"
flake8 = "^6.0.0"
wheel = "^0.40"
pytest-depends = "^1.0.1"
pytest-lazy-fixture = "^0.6.3"
coverage = "^7.2"
pytest-cov = "^4.0.0"
moto = {extras = ["sts"], version = "^4.1.4"}
deepdiff = "^6.2.0"
Sphinx = "5.1.1"

[tool.poetry.scripts]
worker = 'tfworker.cli:cli'

[tool.poetry.group.dev.dependencies]
pytest-timeout = "2.1.0"

[tool.pytest.ini_options]
addopts = "--capture=sys --cov=tfworker --cov-report="

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
