import os
import tempfile
from typing import Any, Dict, Union

import yaml
from pydantic import ValidationError

import tfworker.util.log as log
from tfworker.custom_types.config_file import DefinitionsSource
from tfworker.definitions.prepare import copy, get_coppier
from tfworker.exceptions import DefinitionsSourceError
from tfworker.util.system import pipe_exec


def apply_definitions_sources(
    merged_config: Dict[str, Any],
    deployment: str,
    repository_path: str,
) -> None:
    """
    Run each definitions source and insert the definitions it prints.

    Sources run in config order, so later sources see earlier sources' output.
    Each source is fetched to a temporary directory that is removed after its command runs.

    Args:
        merged_config (Dict[str, Any]): the merged, unvalidated config; updated in place
        deployment (str): the deployment, passed to commands as WORKER_DEPLOYMENT
        repository_path (str): the root that relative source paths resolve from

    Raises:
        DefinitionsSourceError: a source failed or its output can't be applied
        ValidationError: a source block is invalid
    """
    origins: Dict[str, str] = {}
    for name, body in merged_config["definitions_sources"].items():
        try:
            source = DefinitionsSource.model_validate(body)
        except ValidationError as e:
            e.ctx = ("definitions source", name)
            raise
        definitions = merged_config.get("definitions") or {}
        if source.after is not None and source.after not in definitions:
            raise DefinitionsSourceError(
                f"definitions source {name}: after names unknown definition {source.after}"
            )
        with tempfile.TemporaryDirectory(prefix="tfworker-source-") as copy_dir:
            _fetch(name, source, repository_path, copy_dir)
            generated = _run(name, source, copy_dir, deployment)
        for def_name, definition in generated.items():
            _check_collision(name, def_name, definitions, origins)
            origins[def_name] = name
            _inherit_location(definition, source)
        merged_config["definitions"] = _insert(definitions, generated, source.after)


def _fetch(
    name: str, source: DefinitionsSource, repository_path: str, copy_dir: str
) -> None:
    """Copy the source into copy_dir, the same way definitions are fetched."""
    try:
        copier = get_coppier(source.path, repository_path, conflicts=[])
        copy(copier, copy_dir, _remote_options(source))
    except (NotImplementedError, FileNotFoundError, FileExistsError, RuntimeError) as e:
        raise DefinitionsSourceError(
            f"definitions source {name}: unable to fetch {source.path}: {e}"
        ) from e


def _run(
    name: str, source: DefinitionsSource, copy_dir: str, deployment: str
) -> Dict[str, Dict[str, Any]]:
    """Run the source's command in its copy and parse the printed definitions."""
    log.debug(f"running definitions source {name}: {source.command}")
    env = {**os.environ, "WORKER_DEPLOYMENT": deployment}
    try:
        rc, stdout, stderr = pipe_exec(source.command, cwd=copy_dir, env=env)
    except OSError as e:
        raise DefinitionsSourceError(
            f"definitions source {name}: unable to run {source.command}: {e}"
        ) from e
    stderr_text = stderr.decode("utf-8", errors="replace")
    if rc != 0:
        raise DefinitionsSourceError(
            f"definitions source {name}: {source.command} exited {rc}\n{stderr_text}"
        )
    if stderr_text:
        log.debug(f"definitions source {name} stderr:\n{stderr_text}")
    return _parse(name, stdout.decode("utf-8"))


def _parse(name: str, output: str) -> Dict[str, Dict[str, Any]]:
    """Parse command output into a mapping of definition name to body."""
    try:
        parsed = yaml.safe_load(output)
    except yaml.YAMLError as e:
        raise DefinitionsSourceError(
            f"definitions source {name}: output is not valid YAML or JSON: {e}"
        ) from e
    if parsed is None:
        return {}
    if not isinstance(parsed, dict):
        raise DefinitionsSourceError(
            f"definitions source {name}: output must be a mapping of definitions"
        )
    for def_name, body in parsed.items():
        if body is None:
            parsed[def_name] = body = {}
        if not isinstance(def_name, str) or not isinstance(body, dict):
            raise DefinitionsSourceError(
                f"definitions source {name}: {def_name!r} must be a name mapped to a definition"
            )
    return parsed


def _check_collision(
    source_name: str,
    def_name: str,
    definitions: Dict[str, Any],
    origins: Dict[str, str],
) -> None:
    """Fail when a generated name is already defined."""
    if def_name in origins:
        raise DefinitionsSourceError(
            f"definition {def_name} generated by both definitions sources "
            f"{origins[def_name]} and {source_name}"
        )
    if def_name in definitions:
        raise DefinitionsSourceError(
            f"definitions source {source_name}: generated definition {def_name} "
            "conflicts with a configured definition"
        )


def _inherit_location(definition: Dict[str, Any], source: DefinitionsSource) -> None:
    """Point a definition without its own path at the source."""
    if "path" in definition:
        return
    definition["path"] = source.path
    if source.remote_path_options and "remote_path_options" not in definition:
        definition["remote_path_options"] = _remote_options(source)


def _remote_options(source: DefinitionsSource) -> Dict[str, Any]:
    """The source's remote_path_options without unset fields."""
    if source.remote_path_options is None:
        return {}
    return source.remote_path_options.model_dump(exclude_none=True)


def _insert(
    definitions: Dict[str, Any], generated: Dict[str, Any], after: Union[str, None]
) -> Dict[str, Any]:
    """Return definitions with generated placed after the anchor, or at the end."""
    if after is None:
        return {**definitions, **generated}
    result = {}
    for name, body in definitions.items():
        result[name] = body
        if name == after:
            result.update(generated)
    return result
